### ISSUE TITLE
matlab cmakelists GOP is included

### ISSUE THREAD

**Issue by lolongcovas** [philkr/lpo#1]
Hi,

Does this library require GOP library? because the **cmakelists.txt** of matlab folder contains:

<li>add_library( gop_mex SHARED gop_mex.cpp )
<li>target_link_libraries( gop_mex util imgproc learning contour segmentation proposals gomp )

**Comment by philkr** [comment]
I didn’t update the matlab wrapper yet. I’ll do that after ICCV. For now, I’d recommend to use the python wrapper and generate hf5 files.

Philipp

**Comment by lolongcovas** [comment]
Thanks
