### ISSUE TITLE
Simple C++ example of process one image

### ISSUE THREAD

**Issue by drozdvadym** [philkr/lpo#17]
Hello. I am very excited of  your previous approach: Geodesic Object Proposals. And there you propose good example of using library in C++ code. Can you give some part of code for use this library? I found that they very similar.

Thank you.

**Comment by drozdvadym** [comment]
Hi there! I have closely read python examples and this was helped me to implement example in C++.

**Comment by n3011** [comment]
@drozdvadym  could you please share the c++ example??
