### ISSUE TITLE
Typos in CMakeLists.txt

### ISSUE THREAD

**Issue by bittnt** [philkr/lpo#2]
Hi, @philkr 
I think there is a typos in matlab/CMakeLists.txt

add_library( gop_mex SHARED gop_mex.cpp )
target_link_libraries( gop_mex util imgproc learning contour segmentation proposals gomp )

should be

add_library( lpo_mex SHARED lpo_mex )
target_link_libraries( lpo_mex util imgproc learning contour segmentation proposals gomp )

As you do not have gop_mex.cpp in this project, Do you?

**Comment by philkr** [comment]
As mentioned in #1 I didn't update the matlab wrapper yet. I'll do that as soon as I have time. Also feel free to PR one if you want.
