### ISSUE TITLE
ImportError: No module named python.lpo

### ISSUE THREAD

**Issue by huayong** [philkr/lpo#3]
I followed the install pipeline and no error. But at last when I  run the command-''bash eval_all.sh', the console printed "ImportError: No module named pylab". Then I changed the eval_all.sh script file, all python3 to python. Though there wasn't previous error, the console printed a new error, "ImportError: No module named python.lpo". Now I had no idea and hope you could help me. Thanks.

**Comment by philkr** [comment]
pylab was the matploltib dependency that I forgot to remove. c719f097977b6192137b67ae405c69cc186a5bc6 should fix this. I also added a section in the readme on how to add the dataset directories so that they can be found in python.

**Comment by rbgirshick** [comment]
After following the instructions in the readme, this is what I see when I do `bash eval_all.sh`:

```
No valid location for lpo.so found! Tried looking in:
/mnt/data/rbg/lpo-tmp/build
/mnt/data/rbg/lpo-tmp/build/release
/mnt/data/rbg/lpo-tmp/build/debug
/mnt/data/rbg/lpo-tmp/build/clang
Traceback (most recent call last):
  File "train_lpo.py", line 28, in <module>
    from lpo import *
  File "/mnt/data/rbg/lpo-tmp/src/lpo.py", line 45, in <module>
    from python.lpo import *
ImportError: No module named 'python'
```

(repeated many times)

`find . -name "lpo.so"` returns no results.

**Comment by philkr** [comment]
Thank you Ross, I forgot to mention the USE_PYTHON flag.
Use -DUSE_PYTHON=ON when calling cmake.

**Comment by mtrth** [comment]
I followed the instructions in the readme and compiled with  -DUSE_PYTHON=2 , when I do bash eval_all.sh I get error:

Traceback (most recent call last):
  File "train_lpo.py", line 31, in <module>
    from lpo import *
  File "/home/revathy/lpo-release/src/lpo.py", line 45, in <module>
    from python.lpo import *
ImportError: dynamic module does not define init function (PyInit_lpo)

hope you could help me. Thanks.
