### ISSUE TITLE
How to fix 'ValueError: Unknown model type 'GlobalCRFModel' problem?

### ISSUE THREAD

**Issue by b2220333** [philkr/lpo#4]
Hello, thanks for sharing codes!
I compile your code success with python 2.7.
I also change python3 to python in eval_all.sh file.
When I run eval_all.sh, it shows:

Traceback (most recent call last):
  File "train_lpo.py", line 129, in <module>
    prop.load(save_name)
ValueError: Unknown model type 'GlobalCRFModel'!
Traceback (most recent call last):
  File "train_lpo.py", line 129, in <module>
    prop.load(save_name)
ValueError: Unknown model type 'GlobalCRFModel'!
Traceback (most recent call last):
  File "train_lpo.py", line 129, in <module>
    prop.load(save_name)
ValueError: Unknown model type 'GlobalCRFModel'!
Traceback (most recent call last):
  File "train_lpo.py", line 129, in <module>
    prop.load(save_name)
ValueError: Unknown model type 'GlobalCRFModel'!
Traceback (most recent call last):
  File "train_lpo.py", line 129, in <module>
    prop.load(save_name)
ValueError: Unknown model type 'GlobalCRFModel'!
Traceback (most recent call last):
  File "train_lpo.py", line 129, in <module>
    prop.load(save_name)
ValueError: Unknown model type 'GlobalCRFModel'!
sam@sam-desktop:~/code/download/Segmentation/lpo/src$ 

How to solve it?
Thank you very much~

**Comment by philkr** [comment]
What OS and compiler do you use? I heard a few people reporting this, but was unable to reproduce it on my machine this far.

**Comment by b2220333** [comment]
I use Ubuntu 12.04 64bits.
gcc 4.6.3
g++ 4.8.1

**Comment by philkr** [comment]
I was finally able to reproduce it on my mac with clang. It seems the random initialization order of static variables caused it. It should be fixed in 69560dad499de1560278f72d4d8bd9b7d9d67c20. Let me know if you have any further issues.

**Comment by b2220333** [comment]
Wow, thank you~
I have a small question about I already have a version of your code.
How could I update to the latest version?
I found that git clone can only download into new directory.

**Comment by b2220333** [comment]
I found that 'git pull' can update to the latest version.
Now this problem is solved, but it show another problem.
I will open another issue to solve it.
Thank you~~
